openapi: '3.0.2'
info:
  title: API with 2 endpoints to fetch all the crypto currency market updates
  version: '1.0'
servers:
  - url: "/api"
paths:
  /fetch_updates:
    get:
      operationId: "markets.fetch_updates"
      summary: " To get all the Market updates Summary"
      
      tags:
        - Array
      security:
        - basic: []  
      responses:
        '200':
          description: Successful

  /fetch_updates/summary:
    get:
      operationId: "markets.summary_updates"
      summary: " To get the specific market's update Summary"
      
      tags:
        - Array
      security:
        - basic: []  
      parameters:
        - name: marketname
          schema:
            type: string
          in: query
          required: true
          description: "Provide specific market name"
      responses:
        '200':
          description: successful         

components:
  securitySchemes:
    basic:
      type: http
      scheme: basic 
      x-basicInfoFunc: markets.basic_auth      
